#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  bMotorReflected[motorD] = true;

  return;
}
int scaleForMotor(int joyValue)
{
  const int threshold = 5;
  const int MAX_MOTOR_VAL = 75;
  const float MAX_JOY_VAL = 127;

  if (abs(joyValue)<threshold)
  {
    return 0;
  }
  int direction = joyValue/abs(joyValue);
  float ratio = ((joyValue*joyValue) / (MAX_JOY_VAL*MAX_JOY_VAL));
  int scaledVal = (ratio*MAX_MOTOR_VAL)*direction;

  return scaledVal;
}
task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase
  	float scale = 2
  	-; //scale the motors down
  	while (true)
	{
		getJoystickSettings(joystick);


	if (joy1Btn(5) == 1 || joy1Btn(6) == 1)
	{
	//  servo[servo1] = ServoValue [servo1] + increase;
		// servo[servo2] = ServoValue [servo2] - increase;
	}

	if (joy1Btn(7) == 1 || joy1Btn(8) == 1)
	{
	  //servo[servo1] = ServoValue [servo1] - increase;
		// servo[servo2] = ServoValue [servo2] + increase;
	}

		motor[motorE] = scaleForMotor(joystick.joy1_y1)*scale; //rgt
		motor[motorD] = scaleForMotor(joystick.joy1_y2)*scale; //rgt

/*
   i-f (joystick.joy1_TopHat == 0)
		{
		 increase = increase + 1;
	  }

  	if (joystick.joy1_TopHat == 4)
		{
		 increase = increase - 1;
	  }
*/
		/*
		setServoTarget(servoName) = 130;
		setServoTarget(servoName) = 130;
*/

if(joy1Btn(5))//boost mode

		{
			scale = 2;//.4
		}

		if(joy1Btn(9))//slow mode

		{
			scale = .1;//.4
		}
		if(joy1Btn(10)) //normal mode
		{
			scale = .5; //1.1
		}

		/* Ex: moving arms up
		if(joy1Btn(6)&& ServoValue[servo1]<260 &&ServoValue[servo4]>117)
		{
				servo[servo1] = ServoValue[servo1]+4;
				servo[servo4] = ServoValue[servo4]-4;
		}*/

  }
}
